project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Siwen Zhang"
  description: "Bioinformatics, Translational AI, Clinical Genomics"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Bioinformatics
        href: professional_activities.qmd
      # - text: Projects
      #   href: projects.qmd
      - text: Skills
        href: personal_skills.qmd
      - text: Publications
        href: publications.qmd
      - text: Resumé
        href: curriculum.qmd
    right:
      - icon: github
        href: https://github.com/ssswzh
      - icon: envelope
        href: "mailto:aristazhang521@outlook.com"

format:
  html:
    theme: cosmo
    css:
      - custom.css
    toc: true
    linkcolor: black

